/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.TheLoaiBUS;
import DTO.TheLoaiDTO;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lộc
 */
public class DanhMuc extends javax.swing.JFrame {
    
    private DefaultTableModel modelTheLoai = new DefaultTableModel();
    private DefaultTableModel searchTheLoai;
    private int modeTL;
    
    
    private TheLoaiBUS theloaibus=new TheLoaiBUS();

    /**
     * Creates new form DanhMuc
     */
    public DanhMuc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        formTheLoai = new RoundedPanel(50, new Color(20, 20, 50));
        jLabel2 = new javax.swing.JLabel();
        txMaTL = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txTenTL = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTheLoai = new javax.swing.JTable();
        btThemTL = new javax.swing.JButton();
        btSuaTL = new javax.swing.JButton();
        btXoaTL = new javax.swing.JButton();
        btTimTL = new javax.swing.JButton();
        jPanel2 = new RoundedPanel(10, new Color(68, 187, 236));
        jLabel1 = new javax.swing.JLabel();
        btClearTL = new javax.swing.JButton();
        btAllTL = new javax.swing.JButton();
        btConfirmTL = new javax.swing.JButton();
        btCancelTL = new javax.swing.JButton();
        formTacGia = new RoundedPanel(50, new Color(20, 20, 50));
        jLabel4 = new javax.swing.JLabel();
        txMaTG = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txTenTG = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbTacGia = new javax.swing.JTable();
        btThemTG = new javax.swing.JButton();
        btSuaTG = new javax.swing.JButton();
        btXoaTG = new javax.swing.JButton();
        btTimTG = new javax.swing.JButton();
        jPanel3 = new RoundedPanel(10, new Color(68, 187, 236));
        jLabel6 = new javax.swing.JLabel();
        btClearTG = new javax.swing.JButton();
        btAllTG = new javax.swing.JButton();
        btConfirmTG = new javax.swing.JButton();
        btCancelTG = new javax.swing.JButton();
        formNhaXuatBan = new RoundedPanel(50, new Color(20, 20, 50));
        jLabel7 = new javax.swing.JLabel();
        txMaNXB = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txTenNXB = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbNhaXuatBan = new javax.swing.JTable();
        btThemNXB = new javax.swing.JButton();
        btSuaNXB = new javax.swing.JButton();
        btXoaNXB = new javax.swing.JButton();
        btTimNXB = new javax.swing.JButton();
        jPanel4 = new RoundedPanel(10, new Color(68, 187, 236));
        jLabel9 = new javax.swing.JLabel();
        btClearNXB = new javax.swing.JButton();
        btAllNXB = new javax.swing.JButton();
        btConfirmNXB = new javax.swing.JButton();
        btCancelNXB = new javax.swing.JButton();
        formTaiKhoan = new RoundedPanel(50, new Color(20, 20, 50));
        jLabel10 = new javax.swing.JLabel();
        txUsername = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txPassword = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbTaiKhoan = new javax.swing.JTable();
        btThemTK = new javax.swing.JButton();
        btSuaTK = new javax.swing.JButton();
        btXoaTK = new javax.swing.JButton();
        btTimTK = new javax.swing.JButton();
        jPanel9 = new RoundedPanel(10, new Color(68, 187, 236));
        jLabel12 = new javax.swing.JLabel();
        btClearTK = new javax.swing.JButton();
        btAllTK = new javax.swing.JButton();
        btConfirmTK = new javax.swing.JButton();
        btCancelTK = new javax.swing.JButton();
        formNhaCungCap = new RoundedPanel(50, new Color(20, 20, 50));
        jLabel13 = new javax.swing.JLabel();
        txMaNCC = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txTenNCC = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbNhaCungCap = new javax.swing.JTable();
        btThemNCC = new javax.swing.JButton();
        btSuaNCC = new javax.swing.JButton();
        btXoaNCC = new javax.swing.JButton();
        btTimNCC = new javax.swing.JButton();
        jPanel11 = new RoundedPanel(10, new Color(68, 187, 236));
        jLabel15 = new javax.swing.JLabel();
        btClearNCC = new javax.swing.JButton();
        btAllNCC = new javax.swing.JButton();
        btConfirmNCC = new javax.swing.JButton();
        btCancelNCC = new javax.swing.JButton();
        formLoiPhat = new RoundedPanel(50, new Color(20, 20, 50));
        jLabel16 = new javax.swing.JLabel();
        txMaLP = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txTenLP = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbLoiPhat = new javax.swing.JTable();
        btThemLP = new javax.swing.JButton();
        btSuaLP = new javax.swing.JButton();
        btXoaLP = new javax.swing.JButton();
        btTimLP = new javax.swing.JButton();
        jPanel13 = new RoundedPanel(10, new Color(68, 187, 236));
        jLabel18 = new javax.swing.JLabel();
        btClearLP = new javax.swing.JButton();
        btAllLP = new javax.swing.JButton();
        btConfirmLP = new javax.swing.JButton();
        btCancelLP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(43, 10));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(30, 29, 65));

        formTheLoai.setBackground(new java.awt.Color(30, 29, 65));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mã thể loại:");

        txMaTL.setBackground(new java.awt.Color(27, 26, 67));
        txMaTL.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tên thể loại:");

        txTenTL.setBackground(new java.awt.Color(27, 26, 67));
        txTenTL.setForeground(new java.awt.Color(255, 255, 255));

        tbTheLoai.setBackground(new java.awt.Color(27, 26, 67));
        tbTheLoai.setForeground(new java.awt.Color(255, 255, 255));
        tbTheLoai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã thể loại", "Tên thể loại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbTheLoai.setGridColor(new java.awt.Color(255, 255, 255));
        tbTheLoai.setRowHeight(18);
        tbTheLoai.setShowGrid(true);
        tbTheLoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTheLoaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTheLoai);

        btThemTL.setBackground(new java.awt.Color(27, 26, 67));
        btThemTL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btThemTL.setForeground(new java.awt.Color(255, 255, 255));
        btThemTL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/add.png"))); // NOI18N
        btThemTL.setText("Thêm");
        btThemTL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btThemTL.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btSuaTL.setBackground(new java.awt.Color(27, 26, 67));
        btSuaTL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSuaTL.setForeground(new java.awt.Color(255, 255, 255));
        btSuaTL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/edit.png"))); // NOI18N
        btSuaTL.setText("Sửa");
        btSuaTL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btSuaTL.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btXoaTL.setBackground(new java.awt.Color(27, 26, 67));
        btXoaTL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btXoaTL.setForeground(new java.awt.Color(255, 255, 255));
        btXoaTL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/minus.png"))); // NOI18N
        btXoaTL.setText("Xoá");
        btXoaTL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btXoaTL.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btTimTL.setBackground(new java.awt.Color(27, 26, 67));
        btTimTL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTimTL.setForeground(new java.awt.Color(255, 255, 255));
        btTimTL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/search.png"))); // NOI18N
        btTimTL.setText("Tìm");
        btTimTL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btTimTL.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jPanel2.setBackground(new java.awt.Color(20, 20, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THỂ LOẠI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btClearTL.setBackground(new java.awt.Color(255, 153, 51));
        btClearTL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btClearTL.setForeground(new java.awt.Color(255, 255, 255));
        btClearTL.setText("Tạo mới");
        btClearTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearTLActionPerformed(evt);
            }
        });

        btAllTL.setBackground(new java.awt.Color(165, 201, 63));
        btAllTL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAllTL.setForeground(new java.awt.Color(255, 255, 255));
        btAllTL.setText("Tất cả");

        btConfirmTL.setBackground(new java.awt.Color(165, 201, 63));
        btConfirmTL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btConfirmTL.setForeground(new java.awt.Color(255, 255, 255));
        btConfirmTL.setText("Xác nhận");

        btCancelTL.setBackground(new java.awt.Color(206, 81, 80));
        btCancelTL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCancelTL.setForeground(new java.awt.Color(255, 255, 255));
        btCancelTL.setText("Huỷ");

        javax.swing.GroupLayout formTheLoaiLayout = new javax.swing.GroupLayout(formTheLoai);
        formTheLoai.setLayout(formTheLoaiLayout);
        formTheLoaiLayout.setHorizontalGroup(
            formTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formTheLoaiLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(formTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(formTheLoaiLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btConfirmTL, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btCancelTL, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formTheLoaiLayout.createSequentialGroup()
                        .addGroup(formTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(formTheLoaiLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txTenTL))
                                .addGroup(formTheLoaiLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txMaTL, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(formTheLoaiLayout.createSequentialGroup()
                                .addComponent(btClearTL, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btAllTL, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(formTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btTimTL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btThemTL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btSuaTL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btXoaTL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(24, 29, Short.MAX_VALUE))
        );
        formTheLoaiLayout.setVerticalGroup(
            formTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formTheLoaiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btThemTL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btSuaTL, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txMaTL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btXoaTL, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txTenTL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btTimTL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btClearTL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAllTL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formTheLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConfirmTL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelTL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        btConfirmTL.setVisible(false);
        btCancelTL.setVisible(false);

        formTacGia.setBackground(new java.awt.Color(30, 29, 65));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mã tác giả:");

        txMaTG.setBackground(new java.awt.Color(27, 26, 67));
        txMaTG.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tên tác giả:");

        txTenTG.setBackground(new java.awt.Color(27, 26, 67));
        txTenTG.setForeground(new java.awt.Color(255, 255, 255));

        tbTacGia.setBackground(new java.awt.Color(27, 26, 67));
        tbTacGia.setForeground(new java.awt.Color(255, 255, 255));
        tbTacGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã tác giả", "Tên tác giả"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbTacGia.setGridColor(new java.awt.Color(255, 255, 255));
        tbTacGia.setRowHeight(18);
        tbTacGia.setShowGrid(true);
        jScrollPane2.setViewportView(tbTacGia);

        btThemTG.setBackground(new java.awt.Color(27, 26, 67));
        btThemTG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btThemTG.setForeground(new java.awt.Color(255, 255, 255));
        btThemTG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/add.png"))); // NOI18N
        btThemTG.setText("Thêm");
        btThemTG.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btThemTG.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btSuaTG.setBackground(new java.awt.Color(27, 26, 67));
        btSuaTG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSuaTG.setForeground(new java.awt.Color(255, 255, 255));
        btSuaTG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/edit.png"))); // NOI18N
        btSuaTG.setText("Sửa");
        btSuaTG.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btSuaTG.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btXoaTG.setBackground(new java.awt.Color(27, 26, 67));
        btXoaTG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btXoaTG.setForeground(new java.awt.Color(255, 255, 255));
        btXoaTG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/minus.png"))); // NOI18N
        btXoaTG.setText("Xoá");
        btXoaTG.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btXoaTG.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btTimTG.setBackground(new java.awt.Color(27, 26, 67));
        btTimTG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTimTG.setForeground(new java.awt.Color(255, 255, 255));
        btTimTG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/search.png"))); // NOI18N
        btTimTG.setText("Tìm");
        btTimTG.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btTimTG.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jPanel3.setBackground(new java.awt.Color(20, 20, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("TÁC GIẢ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btClearTG.setBackground(new java.awt.Color(255, 153, 51));
        btClearTG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btClearTG.setForeground(new java.awt.Color(255, 255, 255));
        btClearTG.setText("Tạo mới");

        btAllTG.setBackground(new java.awt.Color(165, 201, 63));
        btAllTG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAllTG.setForeground(new java.awt.Color(255, 255, 255));
        btAllTG.setText("Tất cả");

        btConfirmTG.setBackground(new java.awt.Color(165, 201, 63));
        btConfirmTG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btConfirmTG.setForeground(new java.awt.Color(255, 255, 255));
        btConfirmTG.setText("Xác nhận");

        btCancelTG.setBackground(new java.awt.Color(206, 81, 80));
        btCancelTG.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCancelTG.setForeground(new java.awt.Color(255, 255, 255));
        btCancelTG.setText("Huỷ");

        javax.swing.GroupLayout formTacGiaLayout = new javax.swing.GroupLayout(formTacGia);
        formTacGia.setLayout(formTacGiaLayout);
        formTacGiaLayout.setHorizontalGroup(
            formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formTacGiaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(formTacGiaLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btConfirmTG, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btCancelTG, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formTacGiaLayout.createSequentialGroup()
                        .addGroup(formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(formTacGiaLayout.createSequentialGroup()
                                    .addGroup(formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txMaTG)
                                        .addComponent(txTenTG))))
                            .addGroup(formTacGiaLayout.createSequentialGroup()
                                .addComponent(btClearTG, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btAllTG, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btTimTG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btThemTG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btSuaTG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btXoaTG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(24, 29, Short.MAX_VALUE))
        );
        formTacGiaLayout.setVerticalGroup(
            formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formTacGiaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btThemTG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btSuaTG, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txMaTG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btXoaTG, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txTenTG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btTimTG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btClearTG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAllTG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formTacGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConfirmTG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelTG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );

        btConfirmTG.setVisible(false);
        btCancelTG.setVisible(false);

        formNhaXuatBan.setBackground(new java.awt.Color(30, 29, 65));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mã NXB:");

        txMaNXB.setBackground(new java.awt.Color(27, 26, 67));
        txMaNXB.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tên NXB:");

        txTenNXB.setBackground(new java.awt.Color(27, 26, 67));
        txTenNXB.setForeground(new java.awt.Color(255, 255, 255));

        tbNhaXuatBan.setBackground(new java.awt.Color(27, 26, 67));
        tbNhaXuatBan.setForeground(new java.awt.Color(255, 255, 255));
        tbNhaXuatBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã nhà xuất bản", "Tên nhà xuất bản"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbNhaXuatBan.setGridColor(new java.awt.Color(255, 255, 255));
        tbNhaXuatBan.setRowHeight(18);
        tbNhaXuatBan.setShowGrid(true);
        jScrollPane3.setViewportView(tbNhaXuatBan);

        btThemNXB.setBackground(new java.awt.Color(27, 26, 67));
        btThemNXB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btThemNXB.setForeground(new java.awt.Color(255, 255, 255));
        btThemNXB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/add.png"))); // NOI18N
        btThemNXB.setText("Thêm");
        btThemNXB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btThemNXB.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btSuaNXB.setBackground(new java.awt.Color(27, 26, 67));
        btSuaNXB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSuaNXB.setForeground(new java.awt.Color(255, 255, 255));
        btSuaNXB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/edit.png"))); // NOI18N
        btSuaNXB.setText("Sửa");
        btSuaNXB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btSuaNXB.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btXoaNXB.setBackground(new java.awt.Color(27, 26, 67));
        btXoaNXB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btXoaNXB.setForeground(new java.awt.Color(255, 255, 255));
        btXoaNXB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/minus.png"))); // NOI18N
        btXoaNXB.setText("Xoá");
        btXoaNXB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btXoaNXB.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btTimNXB.setBackground(new java.awt.Color(27, 26, 67));
        btTimNXB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTimNXB.setForeground(new java.awt.Color(255, 255, 255));
        btTimNXB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/search.png"))); // NOI18N
        btTimNXB.setText("Tìm");
        btTimNXB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btTimNXB.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jPanel4.setBackground(new java.awt.Color(20, 20, 50));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("NHÀ XUẤT BẢN");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btClearNXB.setBackground(new java.awt.Color(255, 153, 51));
        btClearNXB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btClearNXB.setForeground(new java.awt.Color(255, 255, 255));
        btClearNXB.setText("Tạo mới");

        btAllNXB.setBackground(new java.awt.Color(165, 201, 63));
        btAllNXB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAllNXB.setForeground(new java.awt.Color(255, 255, 255));
        btAllNXB.setText("Tất cả");

        btConfirmNXB.setBackground(new java.awt.Color(165, 201, 63));
        btConfirmNXB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btConfirmNXB.setForeground(new java.awt.Color(255, 255, 255));
        btConfirmNXB.setText("Xác nhận");

        btCancelNXB.setBackground(new java.awt.Color(206, 81, 80));
        btCancelNXB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCancelNXB.setForeground(new java.awt.Color(255, 255, 255));
        btCancelNXB.setText("Huỷ");

        javax.swing.GroupLayout formNhaXuatBanLayout = new javax.swing.GroupLayout(formNhaXuatBan);
        formNhaXuatBan.setLayout(formNhaXuatBanLayout);
        formNhaXuatBanLayout.setHorizontalGroup(
            formNhaXuatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formNhaXuatBanLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(formNhaXuatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(formNhaXuatBanLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btConfirmNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btCancelNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formNhaXuatBanLayout.createSequentialGroup()
                        .addGroup(formNhaXuatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formNhaXuatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(formNhaXuatBanLayout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txTenNXB))
                                .addGroup(formNhaXuatBanLayout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txMaNXB))
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(formNhaXuatBanLayout.createSequentialGroup()
                                .addComponent(btClearNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btAllNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(formNhaXuatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btTimNXB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btThemNXB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btSuaNXB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btXoaNXB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(24, 29, Short.MAX_VALUE))
        );
        formNhaXuatBanLayout.setVerticalGroup(
            formNhaXuatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formNhaXuatBanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formNhaXuatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btThemNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formNhaXuatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btSuaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txMaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formNhaXuatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btXoaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txTenNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formNhaXuatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btTimNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btClearNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAllNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formNhaXuatBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConfirmNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );

        btConfirmNXB.setVisible(false);
        btCancelNXB.setVisible(false);

        formTaiKhoan.setBackground(new java.awt.Color(30, 29, 65));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tên ĐN:");

        txUsername.setBackground(new java.awt.Color(27, 26, 67));
        txUsername.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Mật khẩu:");

        txPassword.setBackground(new java.awt.Color(27, 26, 67));
        txPassword.setForeground(new java.awt.Color(255, 255, 255));

        tbTaiKhoan.setBackground(new java.awt.Color(27, 26, 67));
        tbTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        tbTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tên đăng nhập", "Mật khẩu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbTaiKhoan.setGridColor(new java.awt.Color(255, 255, 255));
        tbTaiKhoan.setRowHeight(18);
        tbTaiKhoan.setShowGrid(true);
        jScrollPane4.setViewportView(tbTaiKhoan);

        btThemTK.setBackground(new java.awt.Color(27, 26, 67));
        btThemTK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btThemTK.setForeground(new java.awt.Color(255, 255, 255));
        btThemTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/add.png"))); // NOI18N
        btThemTK.setText("Thêm");
        btThemTK.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btThemTK.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btSuaTK.setBackground(new java.awt.Color(27, 26, 67));
        btSuaTK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSuaTK.setForeground(new java.awt.Color(255, 255, 255));
        btSuaTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/edit.png"))); // NOI18N
        btSuaTK.setText("Sửa");
        btSuaTK.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btSuaTK.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btXoaTK.setBackground(new java.awt.Color(27, 26, 67));
        btXoaTK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btXoaTK.setForeground(new java.awt.Color(255, 255, 255));
        btXoaTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/minus.png"))); // NOI18N
        btXoaTK.setText("Xoá");
        btXoaTK.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btXoaTK.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btTimTK.setBackground(new java.awt.Color(27, 26, 67));
        btTimTK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTimTK.setForeground(new java.awt.Color(255, 255, 255));
        btTimTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/search.png"))); // NOI18N
        btTimTK.setText("Tìm");
        btTimTK.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btTimTK.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jPanel9.setBackground(new java.awt.Color(20, 20, 50));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("TÀI KHOẢN");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btClearTK.setBackground(new java.awt.Color(255, 153, 51));
        btClearTK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btClearTK.setForeground(new java.awt.Color(255, 255, 255));
        btClearTK.setText("Tạo mới");

        btAllTK.setBackground(new java.awt.Color(165, 201, 63));
        btAllTK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAllTK.setForeground(new java.awt.Color(255, 255, 255));
        btAllTK.setText("Tất cả");

        btConfirmTK.setBackground(new java.awt.Color(165, 201, 63));
        btConfirmTK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btConfirmTK.setForeground(new java.awt.Color(255, 255, 255));
        btConfirmTK.setText("Xác nhận");

        btCancelTK.setBackground(new java.awt.Color(206, 81, 80));
        btCancelTK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCancelTK.setForeground(new java.awt.Color(255, 255, 255));
        btCancelTK.setText("Huỷ");

        javax.swing.GroupLayout formTaiKhoanLayout = new javax.swing.GroupLayout(formTaiKhoan);
        formTaiKhoan.setLayout(formTaiKhoanLayout);
        formTaiKhoanLayout.setHorizontalGroup(
            formTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formTaiKhoanLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(formTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(formTaiKhoanLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btConfirmTK, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btCancelTK, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formTaiKhoanLayout.createSequentialGroup()
                        .addGroup(formTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(formTaiKhoanLayout.createSequentialGroup()
                                    .addGroup(formTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(formTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txPassword)
                                        .addComponent(txUsername))))
                            .addGroup(formTaiKhoanLayout.createSequentialGroup()
                                .addComponent(btClearTK, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btAllTK, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(formTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btTimTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btThemTK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btSuaTK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btXoaTK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        formTaiKhoanLayout.setVerticalGroup(
            formTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formTaiKhoanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btThemTK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btSuaTK, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btXoaTK, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btTimTK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btClearTK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAllTK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConfirmTK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelTK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );

        btConfirmTK.setVisible(false);
        btCancelTK.setVisible(false);

        formNhaCungCap.setBackground(new java.awt.Color(30, 29, 65));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Mã NCC:");

        txMaNCC.setBackground(new java.awt.Color(27, 26, 67));
        txMaNCC.setForeground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tên NCC:");

        txTenNCC.setBackground(new java.awt.Color(27, 26, 67));
        txTenNCC.setForeground(new java.awt.Color(255, 255, 255));

        tbNhaCungCap.setBackground(new java.awt.Color(27, 26, 67));
        tbNhaCungCap.setForeground(new java.awt.Color(255, 255, 255));
        tbNhaCungCap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã nhà cung cấp", "Tên nhà cung cấp"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbNhaCungCap.setGridColor(new java.awt.Color(255, 255, 255));
        tbNhaCungCap.setRowHeight(18);
        tbNhaCungCap.setShowGrid(true);
        jScrollPane5.setViewportView(tbNhaCungCap);

        btThemNCC.setBackground(new java.awt.Color(27, 26, 67));
        btThemNCC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btThemNCC.setForeground(new java.awt.Color(255, 255, 255));
        btThemNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/add.png"))); // NOI18N
        btThemNCC.setText("Thêm");
        btThemNCC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btThemNCC.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btSuaNCC.setBackground(new java.awt.Color(27, 26, 67));
        btSuaNCC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSuaNCC.setForeground(new java.awt.Color(255, 255, 255));
        btSuaNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/edit.png"))); // NOI18N
        btSuaNCC.setText("Sửa");
        btSuaNCC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btSuaNCC.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btXoaNCC.setBackground(new java.awt.Color(27, 26, 67));
        btXoaNCC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btXoaNCC.setForeground(new java.awt.Color(255, 255, 255));
        btXoaNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/minus.png"))); // NOI18N
        btXoaNCC.setText("Xoá");
        btXoaNCC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btXoaNCC.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btTimNCC.setBackground(new java.awt.Color(27, 26, 67));
        btTimNCC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTimNCC.setForeground(new java.awt.Color(255, 255, 255));
        btTimNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/search.png"))); // NOI18N
        btTimNCC.setText("Tìm");
        btTimNCC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btTimNCC.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jPanel11.setBackground(new java.awt.Color(20, 20, 50));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("NHÀ CUNG CẤP");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btClearNCC.setBackground(new java.awt.Color(255, 153, 51));
        btClearNCC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btClearNCC.setForeground(new java.awt.Color(255, 255, 255));
        btClearNCC.setText("Tạo mới");

        btAllNCC.setBackground(new java.awt.Color(165, 201, 63));
        btAllNCC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAllNCC.setForeground(new java.awt.Color(255, 255, 255));
        btAllNCC.setText("Tất cả");

        btConfirmNCC.setBackground(new java.awt.Color(165, 201, 63));
        btConfirmNCC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btConfirmNCC.setForeground(new java.awt.Color(255, 255, 255));
        btConfirmNCC.setText("Xác nhận");

        btCancelNCC.setBackground(new java.awt.Color(206, 81, 80));
        btCancelNCC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCancelNCC.setForeground(new java.awt.Color(255, 255, 255));
        btCancelNCC.setText("Huỷ");

        javax.swing.GroupLayout formNhaCungCapLayout = new javax.swing.GroupLayout(formNhaCungCap);
        formNhaCungCap.setLayout(formNhaCungCapLayout);
        formNhaCungCapLayout.setHorizontalGroup(
            formNhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formNhaCungCapLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(formNhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(formNhaCungCapLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btConfirmNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btCancelNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formNhaCungCapLayout.createSequentialGroup()
                        .addGroup(formNhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(formNhaCungCapLayout.createSequentialGroup()
                                .addGroup(formNhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(formNhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formNhaCungCapLayout.createSequentialGroup()
                                    .addComponent(btClearNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(btAllNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(formNhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btTimNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btThemNCC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btSuaNCC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btXoaNCC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(24, 30, Short.MAX_VALUE))
        );
        formNhaCungCapLayout.setVerticalGroup(
            formNhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formNhaCungCapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formNhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btThemNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formNhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btSuaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txMaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formNhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btXoaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formNhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btTimNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btClearNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAllNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formNhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConfirmNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        btConfirmNCC.setVisible(false);
        btCancelNCC.setVisible(false);

        formLoiPhat.setBackground(new java.awt.Color(30, 29, 65));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Mã lỗi phạt:");

        txMaLP.setBackground(new java.awt.Color(27, 26, 67));
        txMaLP.setForeground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Tên lỗi phạt:");

        txTenLP.setBackground(new java.awt.Color(27, 26, 67));
        txTenLP.setForeground(new java.awt.Color(255, 255, 255));

        tbLoiPhat.setBackground(new java.awt.Color(27, 26, 67));
        tbLoiPhat.setForeground(new java.awt.Color(255, 255, 255));
        tbLoiPhat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã lỗi phạt", "Tên lỗi phạt"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbLoiPhat.setGridColor(new java.awt.Color(255, 255, 255));
        tbLoiPhat.setRowHeight(18);
        tbLoiPhat.setShowGrid(true);
        jScrollPane6.setViewportView(tbLoiPhat);

        btThemLP.setBackground(new java.awt.Color(27, 26, 67));
        btThemLP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btThemLP.setForeground(new java.awt.Color(255, 255, 255));
        btThemLP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/add.png"))); // NOI18N
        btThemLP.setText("Thêm");
        btThemLP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btThemLP.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btSuaLP.setBackground(new java.awt.Color(27, 26, 67));
        btSuaLP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSuaLP.setForeground(new java.awt.Color(255, 255, 255));
        btSuaLP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/edit.png"))); // NOI18N
        btSuaLP.setText("Sửa");
        btSuaLP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btSuaLP.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btXoaLP.setBackground(new java.awt.Color(27, 26, 67));
        btXoaLP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btXoaLP.setForeground(new java.awt.Color(255, 255, 255));
        btXoaLP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/minus.png"))); // NOI18N
        btXoaLP.setText("Xoá");
        btXoaLP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btXoaLP.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btTimLP.setBackground(new java.awt.Color(27, 26, 67));
        btTimLP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btTimLP.setForeground(new java.awt.Color(255, 255, 255));
        btTimLP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconImages/search.png"))); // NOI18N
        btTimLP.setText("Tìm");
        btTimLP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btTimLP.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jPanel13.setBackground(new java.awt.Color(20, 20, 50));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("LỖI PHẠT");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btClearLP.setBackground(new java.awt.Color(255, 153, 51));
        btClearLP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btClearLP.setForeground(new java.awt.Color(255, 255, 255));
        btClearLP.setText("Tạo mới");

        btAllLP.setBackground(new java.awt.Color(165, 201, 63));
        btAllLP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAllLP.setForeground(new java.awt.Color(255, 255, 255));
        btAllLP.setText("Tất cả");

        btConfirmLP.setBackground(new java.awt.Color(165, 201, 63));
        btConfirmLP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btConfirmLP.setForeground(new java.awt.Color(255, 255, 255));
        btConfirmLP.setText("Xác nhận");

        btCancelLP.setBackground(new java.awt.Color(206, 81, 80));
        btCancelLP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCancelLP.setForeground(new java.awt.Color(255, 255, 255));
        btCancelLP.setText("Huỷ");

        javax.swing.GroupLayout formLoiPhatLayout = new javax.swing.GroupLayout(formLoiPhat);
        formLoiPhat.setLayout(formLoiPhatLayout);
        formLoiPhatLayout.setHorizontalGroup(
            formLoiPhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLoiPhatLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(formLoiPhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(formLoiPhatLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btConfirmLP, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btCancelLP, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formLoiPhatLayout.createSequentialGroup()
                        .addGroup(formLoiPhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formLoiPhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(formLoiPhatLayout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txTenLP))
                                .addGroup(formLoiPhatLayout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txMaLP, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(formLoiPhatLayout.createSequentialGroup()
                                .addComponent(btClearLP, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btAllLP, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(formLoiPhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btTimLP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btThemLP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btSuaLP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btXoaLP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(24, 29, Short.MAX_VALUE))
        );
        formLoiPhatLayout.setVerticalGroup(
            formLoiPhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formLoiPhatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formLoiPhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btThemLP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formLoiPhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btSuaLP, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txMaLP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formLoiPhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btXoaLP, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txTenLP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formLoiPhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btTimLP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btClearLP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAllLP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formLoiPhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConfirmLP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelLP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        btConfirmLP.setVisible(false);
        btCancelLP.setVisible(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(formTheLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(formTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(formNhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(formNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(formLoiPhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formNhaXuatBan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(formTacGia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(formTheLoai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(formNhaCungCap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formLoiPhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbTheLoaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTheLoaiMouseClicked
        // TODO add your handling code here:
        int i = tbTheLoai.getSelectedRow();
        if (theloaibus.getList().size() > 0) {
            TheLoaiDTO theloai = new TheLoaiDTO();
            theloai = theloaibus.getList().get(i);
           
            txMaTL.setText(theloai.getMaTheLoai());
            txTenTL.setText(theloai.getTenTheLoai());
            
        }
    }//GEN-LAST:event_tbTheLoaiMouseClicked

    private void btClearTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearTLActionPerformed
        // TODO add your handling code here:
        if(tbTheLoai.isEnabled())
            txMaTL.setText("");
        txTenTL.setText("");
    }//GEN-LAST:event_btClearTLActionPerformed
    
    public void ListTheLoai() throws Exception{
        if(theloaibus.getList()==null)
            theloaibus.listTheLoai();
        ArrayList<TheLoaiDTO> listTL = theloaibus.getList();
        Vector header=new Vector();
        header.add("Mã thể loại");
        header.add("Tên thể loại");
        if (modelTheLoai.getRowCount() == 0) 
                modelTheLoai = new DefaultTableModel(header, 0);
        for(TheLoaiDTO theloai: listTL) {
            Vector row=new Vector();
            row.add(theloai.getMaTheLoai());
            row.add(theloai.getTenTheLoai());
            modelTheLoai.addRow(row);
        }
        tbTheLoai.setModel(modelTheLoai);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DanhMuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DanhMuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DanhMuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DanhMuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DanhMuc danhmuc=new DanhMuc();
                try {
                    danhmuc.ListTheLoai();
                } catch (Exception ex) {
                    Logger.getLogger(DanhMuc.class.getName()).log(Level.SEVERE, null, ex);
                }
                danhmuc.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAllLP;
    private javax.swing.JButton btAllNCC;
    private javax.swing.JButton btAllNXB;
    private javax.swing.JButton btAllTG;
    private javax.swing.JButton btAllTK;
    private javax.swing.JButton btAllTL;
    private javax.swing.JButton btCancelLP;
    private javax.swing.JButton btCancelNCC;
    private javax.swing.JButton btCancelNXB;
    private javax.swing.JButton btCancelTG;
    private javax.swing.JButton btCancelTK;
    private javax.swing.JButton btCancelTL;
    private javax.swing.JButton btClearLP;
    private javax.swing.JButton btClearNCC;
    private javax.swing.JButton btClearNXB;
    private javax.swing.JButton btClearTG;
    private javax.swing.JButton btClearTK;
    private javax.swing.JButton btClearTL;
    private javax.swing.JButton btConfirmLP;
    private javax.swing.JButton btConfirmNCC;
    private javax.swing.JButton btConfirmNXB;
    private javax.swing.JButton btConfirmTG;
    private javax.swing.JButton btConfirmTK;
    private javax.swing.JButton btConfirmTL;
    private javax.swing.JButton btSuaLP;
    private javax.swing.JButton btSuaNCC;
    private javax.swing.JButton btSuaNXB;
    private javax.swing.JButton btSuaTG;
    private javax.swing.JButton btSuaTK;
    private javax.swing.JButton btSuaTL;
    private javax.swing.JButton btThemLP;
    private javax.swing.JButton btThemNCC;
    private javax.swing.JButton btThemNXB;
    private javax.swing.JButton btThemTG;
    private javax.swing.JButton btThemTK;
    private javax.swing.JButton btThemTL;
    private javax.swing.JButton btTimLP;
    private javax.swing.JButton btTimNCC;
    private javax.swing.JButton btTimNXB;
    private javax.swing.JButton btTimTG;
    private javax.swing.JButton btTimTK;
    private javax.swing.JButton btTimTL;
    private javax.swing.JButton btXoaLP;
    private javax.swing.JButton btXoaNCC;
    private javax.swing.JButton btXoaNXB;
    private javax.swing.JButton btXoaTG;
    private javax.swing.JButton btXoaTK;
    private javax.swing.JButton btXoaTL;
    private javax.swing.JPanel formLoiPhat;
    private javax.swing.JPanel formNhaCungCap;
    private javax.swing.JPanel formNhaXuatBan;
    private javax.swing.JPanel formTacGia;
    private javax.swing.JPanel formTaiKhoan;
    private javax.swing.JPanel formTheLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable tbLoiPhat;
    private javax.swing.JTable tbNhaCungCap;
    private javax.swing.JTable tbNhaXuatBan;
    private javax.swing.JTable tbTacGia;
    private javax.swing.JTable tbTaiKhoan;
    private javax.swing.JTable tbTheLoai;
    private javax.swing.JTextField txMaLP;
    private javax.swing.JTextField txMaNCC;
    private javax.swing.JTextField txMaNXB;
    private javax.swing.JTextField txMaTG;
    private javax.swing.JTextField txMaTL;
    private javax.swing.JTextField txPassword;
    private javax.swing.JTextField txTenLP;
    private javax.swing.JTextField txTenNCC;
    private javax.swing.JTextField txTenNXB;
    private javax.swing.JTextField txTenTG;
    private javax.swing.JTextField txTenTL;
    private javax.swing.JTextField txUsername;
    // End of variables declaration//GEN-END:variables
    class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
    }
}
